//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GanttLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GanttLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GanttLanguage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        internal static string Agosto {
            get {
                return ResourceManager.GetString("Agosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string Annulla {
            get {
                return ResourceManager.GetString("Annulla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprile.
        /// </summary>
        internal static string Aprile {
            get {
                return ResourceManager.GetString("Aprile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attivo.
        /// </summary>
        internal static string Attivo {
            get {
                return ResourceManager.GetString("Attivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendario.
        /// </summary>
        internal static string Calendario {
            get {
                return ResourceManager.GetString("Calendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile chiudere l&apos;attività. Controllare gli eventuali errori..
        /// </summary>
        internal static string CANNOT_CLOSE_TASK_IF_OPEN_ISSUE {
            get {
                return ResourceManager.GetString("CANNOT_CLOSE_TASK_IF_OPEN_ISSUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non può dipendere da un antenato..
        /// </summary>
        internal static string CANNOT_DEPENDS_ON_ANCESTORS {
            get {
                return ResourceManager.GetString("CANNOT_DEPENDS_ON_ANCESTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANNOT_MOVE_TASK.
        /// </summary>
        internal static string CANNOT_MOVE_TASK {
            get {
                return ResourceManager.GetString("CANNOT_MOVE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non hai i permessi per modificare l&apos;attività:.
        /// </summary>
        internal static string CANNOT_WRITE {
            get {
                return ResourceManager.GetString("CANNOT_WRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile effettuare l&apos;aggiornamento a causa della mancanzi dei permessi..
        /// </summary>
        internal static string CHANGE_OUT_OF_SCOPE {
            get {
                return ResourceManager.GetString("CHANGE_OUT_OF_SCOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dipendenza circolare..
        /// </summary>
        internal static string CIRCULAR_REFERENCE {
            get {
                return ResourceManager.GetString("CIRCULAR_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice.
        /// </summary>
        internal static string Codice {
            get {
                return ResourceManager.GetString("Codice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Attivià.
        /// </summary>
        internal static string CodiceAttivita {
            get {
                return ResourceManager.GetString("CodiceAttivita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completato.
        /// </summary>
        internal static string Completato {
            get {
                return ResourceManager.GetString("Completato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza sia dati che grafico.
        /// </summary>
        internal static string DatiEGantt {
            get {
                return ResourceManager.GetString("DatiEGantt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione attività.
        /// </summary>
        internal static string DescrizioneAttivita {
            get {
                return ResourceManager.GetString("DescrizioneAttivita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione attività.
        /// </summary>
        internal static string DescrizioneAttività {
            get {
                return ResourceManager.GetString("DescrizioneAttività", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dicembre.
        /// </summary>
        internal static string Dicembre {
            get {
                return ResourceManager.GetString("Dicembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domenica.
        /// </summary>
        internal static string Domenica {
            get {
                return ResourceManager.GetString("Domenica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dur..
        /// </summary>
        internal static string Durata {
            get {
                return ResourceManager.GetString("Durata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La durata è in numero di giorni..
        /// </summary>
        internal static string DurataInGiorni {
            get {
                return ResourceManager.GetString("DurataInGiorni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina attività selezionata.
        /// </summary>
        internal static string Elimina {
            get {
                return ResourceManager.GetString("Elimina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina progetto.
        /// </summary>
        internal static string EliminaProgetto {
            get {
                return ResourceManager.GetString("EliminaProgetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data di fine è una milestone..
        /// </summary>
        internal static string END_IS_MILESTONE {
            get {
                return ResourceManager.GetString("END_IS_MILESTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallito.
        /// </summary>
        internal static string Fallito {
            get {
                return ResourceManager.GetString("Fallito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febbraio.
        /// </summary>
        internal static string Febbraio {
            get {
                return ResourceManager.GetString("Febbraio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        internal static string Fine {
            get {
                return ResourceManager.GetString("Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data di fine attività è una milestone.
        /// </summary>
        internal static string FineMilestone {
            get {
                return ResourceManager.GetString("FineMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GANNT_ERROR_LOADING_DATA_TASK_REMOVED.
        /// </summary>
        internal static string GANNT_ERROR_LOADING_DATA_TASK_REMOVED {
            get {
                return ResourceManager.GetString("GANNT_ERROR_LOADING_DATA_TASK_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore a causa di un discendente di un&apos;attività aperta..
        /// </summary>
        internal static string GANTT_ERROR_DEPENDS_ON_OPEN_TASK {
            get {
                return ResourceManager.GetString("GANTT_ERROR_DEPENDS_ON_OPEN_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore a causa di un discendente di un&apos;attività chiusa..
        /// </summary>
        internal static string GANTT_ERROR_DESCENDANT_OF_CLOSED_TASK {
            get {
                return ResourceManager.GetString("GANTT_ERROR_DESCENDANT_OF_CLOSED_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il caricamento dei dati. Un&apos;attività è stata cancellata..
        /// </summary>
        internal static string GANTT_ERROR_LOADING_DATA_TASK_REMOVED {
            get {
                return ResourceManager.GetString("GANTT_ERROR_LOADING_DATA_TASK_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrimestre.
        /// </summary>
        internal static string GANTT_QUARTER {
            get {
                return ResourceManager.GetString("GANTT_QUARTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t..
        /// </summary>
        internal static string GANTT_QUARTER_SHORT {
            get {
                return ResourceManager.GetString("GANTT_QUARTER_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre.
        /// </summary>
        internal static string GANTT_SEMESTER {
            get {
                return ResourceManager.GetString("GANTT_SEMESTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s..
        /// </summary>
        internal static string GANTT_SEMESTER_SHORT {
            get {
                return ResourceManager.GetString("GANTT_SEMESTER_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settimana.
        /// </summary>
        internal static string GANTT_WEEK {
            get {
                return ResourceManager.GetString("GANTT_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s..
        /// </summary>
        internal static string GANTT_WEEK_SHORT {
            get {
                return ResourceManager.GetString("GANTT_WEEK_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gennaio.
        /// </summary>
        internal static string Gennaio {
            get {
                return ResourceManager.GetString("Gennaio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giorni.
        /// </summary>
        internal static string Giorni {
            get {
                return ResourceManager.GetString("Giorni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giovedì.
        /// </summary>
        internal static string Giovedi {
            get {
                return ResourceManager.GetString("Giovedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giugno.
        /// </summary>
        internal static string Giugno {
            get {
                return ResourceManager.GetString("Giugno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In attesa.
        /// </summary>
        internal static string InAttesa {
            get {
                return ResourceManager.GetString("InAttesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizo.
        /// </summary>
        internal static string Inizio {
            get {
                return ResourceManager.GetString("Inizio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data di inizio attività è una milestone.
        /// </summary>
        internal static string InizioMilestone {
            get {
                return ResourceManager.GetString("InizioMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci un&apos;attività sopra quella selezionata.
        /// </summary>
        internal static string InserisciSopra {
            get {
                return ResourceManager.GetString("InserisciSopra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci un&apos;attività sotto quella selezionata.
        /// </summary>
        internal static string InserisciSotto {
            get {
                return ResourceManager.GetString("InserisciSotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il formato della data inserito, non rispecchiano il formato richiesto..
        /// </summary>
        internal static string INVALID_DATE_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luglio.
        /// </summary>
        internal static string Luglio {
            get {
                return ResourceManager.GetString("Luglio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunedì.
        /// </summary>
        internal static string Lunedi {
            get {
                return ResourceManager.GetString("Lunedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maggio.
        /// </summary>
        internal static string Maggio {
            get {
                return ResourceManager.GetString("Maggio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martedì.
        /// </summary>
        internal static string Martedi {
            get {
                return ResourceManager.GetString("Martedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        internal static string Marzo {
            get {
                return ResourceManager.GetString("Marzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercoledì.
        /// </summary>
        internal static string Mercoledi {
            get {
                return ResourceManager.GetString("Mercoledi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to è una milestone.
        /// </summary>
        internal static string Milestone {
            get {
                return ResourceManager.GetString("Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica le risorse.
        /// </summary>
        internal static string ModificaRisorse {
            get {
                return ResourceManager.GetString("ModificaRisorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non definito.
        /// </summary>
        internal static string NonDefinito {
            get {
                return ResourceManager.GetString("NonDefinito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembre.
        /// </summary>
        internal static string Novembre {
            get {
                return ResourceManager.GetString("Novembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ottobre.
        /// </summary>
        internal static string Ottobre {
            get {
                return ResourceManager.GetString("Ottobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza percorso critico.
        /// </summary>
        internal static string PercorsoCritico {
            get {
                return ResourceManager.GetString("PercorsoCritico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE_SAVE_PROJECT.
        /// </summary>
        internal static string PLEASE_SAVE_PROJECT {
            get {
                return ResourceManager.GetString("PLEASE_SAVE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string Progressi {
            get {
                return ResourceManager.GetString("Progressi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progresso.
        /// </summary>
        internal static string Progresso {
            get {
                return ResourceManager.GetString("Progresso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relazioni.
        /// </summary>
        internal static string Relazioni {
            get {
                return ResourceManager.GetString("Relazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripristina.
        /// </summary>
        internal static string Ripristina {
            get {
                return ResourceManager.GetString("Ripristina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risorsa Associata.
        /// </summary>
        internal static string RisorsaAssociata {
            get {
                return ResourceManager.GetString("RisorsaAssociata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risorse.
        /// </summary>
        internal static string Risorse {
            get {
                return ResourceManager.GetString("Risorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruolo.
        /// </summary>
        internal static string Ruolo {
            get {
                return ResourceManager.GetString("Ruolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabato.
        /// </summary>
        internal static string Sabato {
            get {
                return ResourceManager.GetString("Sabato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        internal static string Salva {
            get {
                return ResourceManager.GetString("Salva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settembre.
        /// </summary>
        internal static string Settembre {
            get {
                return ResourceManager.GetString("Settembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza solo i dati.
        /// </summary>
        internal static string SoloDati {
            get {
                return ResourceManager.GetString("SoloDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza solo il grafico.
        /// </summary>
        internal static string SoloGantt {
            get {
                return ResourceManager.GetString("SoloGantt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sospeso.
        /// </summary>
        internal static string Sospeso {
            get {
                return ResourceManager.GetString("Sospeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposta in giù.
        /// </summary>
        internal static string SpostaGiu {
            get {
                return ResourceManager.GetString("SpostaGiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposta l&apos;attività ad un livello più alto.
        /// </summary>
        internal static string SpostaMenoProfondo {
            get {
                return ResourceManager.GetString("SpostaMenoProfondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposta l&apos;attività ad un livello più basso.
        /// </summary>
        internal static string SpostaPiuProfondo {
            get {
                return ResourceManager.GetString("SpostaPiuProfondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposta in su.
        /// </summary>
        internal static string SpostaSu {
            get {
                return ResourceManager.GetString("SpostaSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa.
        /// </summary>
        internal static string Stampa {
            get {
                return ResourceManager.GetString("Stampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data di inizio è una milestone..
        /// </summary>
        internal static string START_IS_MILESTONE {
            get {
                return ResourceManager.GetString("START_IS_MILESTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato.
        /// </summary>
        internal static string Stato {
            get {
                return ResourceManager.GetString("Stato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest&apos;attività ha delle restrizioni..
        /// </summary>
        internal static string TASK_HAS_CONSTRAINTS {
            get {
                return ResourceManager.GetString("TASK_HAS_CONSTRAINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest&apos;attività ha dipendenze esterne..
        /// </summary>
        internal static string TASK_HAS_EXTERNAL_DEPS {
            get {
                return ResourceManager.GetString("TASK_HAS_EXTERNAL_DEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile spostare attività con diversa profondità..
        /// </summary>
        internal static string TASK_MOVE_INCONSISTENT_LEVEL {
            get {
                return ResourceManager.GetString("TASK_MOVE_INCONSISTENT_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica Attività.
        /// </summary>
        internal static string TitoloModificaAttivita {
            get {
                return ResourceManager.GetString("TitoloModificaAttivita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risorse progetto.
        /// </summary>
        internal static string TitoloModificaRisorse {
            get {
                return ResourceManager.GetString("TitoloModificaRisorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venerdì.
        /// </summary>
        internal static string Venerdi {
            get {
                return ResourceManager.GetString("Venerdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrandisci.
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rimpicciolisci.
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
